# ワークフロー名
name: papers_bot
on:
  push:
  schedule:
    # 定期実行する時間・・・①
    - cron: '0 2 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール・・・②
          python -m pip install arxiv==0.5.1
          python -m pip install pytz
          python -m pip install python-dotenv
      - name: 'Create env file'
        run: |
          touch .env
          echo APP_NAME=${{ secrets.APP_NAME }} >> $GITHUB_OUTPUT
          echo APP_KEY=${{ secrets.APP_KEY }} >> $GITHUB_OUTPUT
          cat .env
      - name: Run script
        run: |
          # 定期実行するファイルを指定・・・③
          python main.py
      - name: Update pickle file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto search
