# ワークフロー名
name: papers_bot
on:
  push:
  schedule:
    # 定期実行する時間・・・①
    - cron: '0 23 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール・・・②
          python -m pip install arxiv==0.5.1
          python -m pip install pytz
          python -m pip install python-dotenv
      - name: 'Create env file'
        run: |
          touch .env
          echo APP_NAME=${{ secrets.APP_NAME }} >> .env
          echo APP_KEY=${{ secrets.APP_KEY }} >> .env
          cat .env
      - name: Run script
        run: |
          # 定期実行するファイルを指定・・・③
          python main.py
